# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI/CD

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: windows-latest

        steps:
            # Checkout
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  submodules: true

            # Cache
            - name: Cache
              uses: actions/cache@v2
              with:
                  path: Library
                  key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                  restore-keys: |
                      Library-

            # Build
            - name: Build project
              uses: game-ci/unity-builder@v2
              env:
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
                  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
              with:
                  targetPlatform: WebGL

            # Output
            - uses: actions/upload-artifact@v2
              with:
                  name: Build
                  path: build

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                  name: Build

            - name: "Deploy to Azure Web App"
              uses: azure/webapps-deploy@v2
              id: deploy-to-webapp
              with:
                  app-name: "indie"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3C9C2AE809B14308951E76BF2E506183 }}
                  package: .
